name: pak_endo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+8

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  video_player: ^2.7.0
  animated_notch_bottom_bar: ^1.0.0
  youtube_player_flutter: ^8.1.2
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  is_first_run: ^1.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  readmore: ^2.2.0
  flutter_media_downloader: ^1.0.0
  firebase_core: ^2.17.0
  device_info_plus: ^9.1.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  change_app_package_name: ^1.1.0
  rename_app: ^1.3.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/logo_white.jpg"
  fullscreen: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo_white.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/login_background.png
    - assets/Logo_Icon.png
    - assets/event1.jpg
    - assets/profile.jpg
    - assets/icons/
    - assets/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-BlackItalic
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
    - family: Poppins-BoldItalic
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf