class MyConsts {
  static const String baseUrl = 'https://pakendo.animetography-blog.com/api/';

  static const List<String> citiesInPakistan = [
    'Abbottabad',
    'Attock',
    'Bahawalnagar',
    'Bahawalpur',
    'Bannu',
    'Bhakkar',
    'Chakwal',
    'Chiniot',
    'Dera Ghazi Khan',
    'Faisalabad',
    'Gujranwala',
    'Gujrat',
    'Hafizabad',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jhang',
    'Jhelum',
    'Karachi',
    'Kasur',
    'Khairpur',
    'Khanewal',
    'Khuzdar',
    'Kohat',
    'Lahore',
    'Larkana',
    'Lodhran',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Multan',
    'Murree',
    'Muzaffarabad',
    'Muzaffargarh',
    'Nawabshah',
    'Okara',
    'Peshawar',
    'Quetta',
    'Rahim Yar Khan',
    'Rawalakot',
    'Rawalpindi',
    'Sahiwal',
    'Sargodha',
    'Sheikhupura',
    'Sialkot',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tando Adam',
    'Vehari',
    'Wah Cantonment',
    'Wazirabad',
  ];
}

enum EventStatus {
  Finished,
  Ongoing,
  Upcoming,
}